Repository wikimedia/hyperswitch, pull requests merged in 2019-05, with the labels that each got.

#102 Update links to source maps in Swagger-UI
  lib/swaggerUI.js
  package.json
Labels: hygene

#103 Bump preq and swagger-router versions; release v0.12.2
  package.json
Labels: release

#104 Stringify the request URI in http filter
  lib/filters/http.js
  package.json
  test/router/buildTree.js
Labels: bug, release
